// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: fibonaccie.proto

package fibonacciegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibonaccie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_fibonaccie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_fibonaccie_proto_rawDescGZIP(), []int{0}
}

func (x *Range) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Range) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FibonaccieItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item uint64 `protobuf:"varint,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *FibonaccieItems) Reset() {
	*x = FibonaccieItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibonaccie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibonaccieItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonaccieItems) ProtoMessage() {}

func (x *FibonaccieItems) ProtoReflect() protoreflect.Message {
	mi := &file_fibonaccie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonaccieItems.ProtoReflect.Descriptor instead.
func (*FibonaccieItems) Descriptor() ([]byte, []int) {
	return file_fibonaccie_proto_rawDescGZIP(), []int{1}
}

func (x *FibonaccieItems) GetItem() uint64 {
	if x != nil {
		return x.Item
	}
	return 0
}

var File_fibonaccie_proto protoreflect.FileDescriptor

var file_fibonaccie_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x23, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x25, 0x0a, 0x0f, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x32, 0x5e,
	0x0a, 0x0a, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x12, 0x50, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x15, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x1f, 0x2e, 0x66, 0x69, 0x62, 0x6f,
	0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x3f,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x6c, 0x61,
	0x64, 0x69, 0x6d, 0x69, 0x72, 0x37, 0x37, 0x37, 0x31, 0x35, 0x2f, 0x66, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x65, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fibonaccie_proto_rawDescOnce sync.Once
	file_fibonaccie_proto_rawDescData = file_fibonaccie_proto_rawDesc
)

func file_fibonaccie_proto_rawDescGZIP() []byte {
	file_fibonaccie_proto_rawDescOnce.Do(func() {
		file_fibonaccie_proto_rawDescData = protoimpl.X.CompressGZIP(file_fibonaccie_proto_rawDescData)
	})
	return file_fibonaccie_proto_rawDescData
}

var file_fibonaccie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fibonaccie_proto_goTypes = []interface{}{
	(*Range)(nil),           // 0: fibonacciegrpc.Range
	(*FibonaccieItems)(nil), // 1: fibonacciegrpc.FibonaccieItems
}
var file_fibonaccie_proto_depIdxs = []int32{
	0, // 0: fibonacciegrpc.Fibonaccie.GetFibonacciStream:input_type -> fibonacciegrpc.Range
	1, // 1: fibonacciegrpc.Fibonaccie.GetFibonacciStream:output_type -> fibonacciegrpc.FibonaccieItems
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fibonaccie_proto_init() }
func file_fibonaccie_proto_init() {
	if File_fibonaccie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fibonaccie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fibonaccie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibonaccieItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fibonaccie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibonaccie_proto_goTypes,
		DependencyIndexes: file_fibonaccie_proto_depIdxs,
		MessageInfos:      file_fibonaccie_proto_msgTypes,
	}.Build()
	File_fibonaccie_proto = out.File
	file_fibonaccie_proto_rawDesc = nil
	file_fibonaccie_proto_goTypes = nil
	file_fibonaccie_proto_depIdxs = nil
}
